name: migrate_external_archive

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Clone source repo
      run: |
        git clone https://github.com/StorywithLove/ZJEMC.git source_repo

    - name: Create target folder
      run: |
        mkdir -p Archive/ZJEMC

    - name: Copy data
      run: |
        cp -r source_repo/Archive/* Archive/ZJEMC/ || true

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add Archive/ZJEMC

        git diff --cached --quiet && echo "No changes" && exit 0

        git commit -m "migrate external Archive → ZJEMC"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GTOKEN }}
